import styled from '@emotion/styled'

import PageContainer from '../../components/PageContainer'
import { dateFormatter } from '../../utils/dateFormatter'
import AboutMe from './components/AboutMe'
import ProfileHeader from './components/ProfileHeader'
import SkillProgressBar from './components/SkillProgressBar'
import Educations from './data/educations.json'
import Experiences from './data/experiences.json'
import ProgrammingSkills from './data/programming_skills.json'
import Qualifications from './data/qualifications.json'

interface SkillBarsProps {
  skillBars: {
    name: string,
    learningLevel: number,
  }[]
}

const Body = styled.div`
  color: #231815;
`

const ProfileDetail = styled.div`
  margin-top: 30px;
  display: flex;
  justify-content: space-between;

  ul {
    margin-bottom: 30px;
  }

  li {
    font-size: 16px;
  }

  .profile_list_sub {
    margin-bottom: 16px;
    font-size: 14px;
    color: #757575;
  }

  @media (max-width: 720px) {
    flex-wrap: wrap;
  }
`

const ProfileDetailSideBlock = styled.section`
  width: 48%;

  @media (max-width: 720px) {
    width: 100%;
  }
`

const ProgrammingSkill = styled.div`
  display: flex;
  flex-wrap: wrap;
  margin-bottom: 30px;
  justify-content: space-between;
`

const GithubContribution = styled.section`
  img {
    width: 100%;
  }

  img:hover {
    opacity: 0.7;
  }
`

const GithubContributionNote = styled.p`
  text-align: right;
  font-size: 14px;
  color: #757575;

  a {
    font-size: 14px;
    color: #757575;
  }

  a:hover {
    color: #61d800;
  }
`

const Profile = () => {
  const Skills = (props: SkillBarsProps) => {
    const SkillBars = props.skillBars

    const SkillItems = SkillBars.map((skillBar, index) => 
      <SkillProgressBar key={index} name={skillBar.name} progress={skillBar.learningLevel} />
    )

    return (
      <ProgrammingSkill>
        {SkillItems}
      </ProgrammingSkill>
    )
  }

  return(
    <PageContainer>
      <Body>
        <AboutMe />
        <ProfileDetail>
          <ProfileDetailSideBlock>
            <ProfileHeader title={'Experience'} />
            <ul>
              {
                Experiences.map((experience) => {
                  const date = `${dateFormatter(experience.from)} - ${dateFormatter(experience.to)}`
                  return <ol key={`${experience.name} ${date}`}>
                    <li>{experience.name} ({date})</li>
                    <li className="profile_list_sub">{experience.description}</li>
                  </ol>
                })
              }
            </ul>
            <ProfileHeader title={'Education'} />
            <ul>
              {
                Educations.map((education) => {
                  const date = `${dateFormatter(education.from)} - ${dateFormatter(education.to)}`
                  return <ol key={`${education.name} ${date}`}>
                    <li>{education.name} ({date})</li>
                    <li className="profile_list_sub">{education.description}</li>
                  </ol>
                })
              }
            </ul>
            <ProfileHeader title={'Qualification'} />
            <ul>
              {
                Qualifications.map((qualification) => {
                  return <ol key={qualification.name}>
                    <li>{qualification.name} ({dateFormatter(qualification.date)})</li>
                    <li className="profile_list_sub">{qualification.description}</li>
                  </ol>
                })
              }
            </ul>
          </ProfileDetailSideBlock>

          <ProfileDetailSideBlock>
            <ProfileHeader title={'Programming Skill'} />
            <Skills skillBars={ProgrammingSkills} />
            <ProfileHeader title={'Github Contribution'} />
            <GithubContribution>
              <a href="https://github.com/okaryo" target="_blank" rel="noopener noreferrer">
                <img
                  src="https://grass-graph.appspot.com/images/okaryo.png" alt="github commits"
                  loading="lazy"
                />
              </a>
              <GithubContributionNote>Generated By <a href="https://github.com/a-know/grass-graph" target="_blank" rel="noopener noreferrer">grass-graph</a></GithubContributionNote>
            </GithubContribution>
          </ProfileDetailSideBlock>
        </ProfileDetail>
      </Body>
    </PageContainer>
  )
}

export default Profile
