name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build_and_deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: setup
      run: npm install -g firebase-tools
    - name: npm install
      run: npm install
    - name: build
      run: npm run build
    - name: deploy
      run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
