name: Build and Deploy

on: 
  push:
    branches: 
      - master

jobs:
  build_firebase_hosting:
    name: build firebase hosting
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: npm install
      run: npm install
    - name: build
      run: npm run build
    - name: persist to workspace
      uses: actions/upload-artifact@master
      with:
        name: build firebase hosting
        path: ./build

  deploy_firebase_hosting:
    name: deploy firebase hosting
    needs: build_firebase_hosting
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: download workspace
      uses: actions/download-artifact@master
      with:
        name: build firebase hosting
        path: ./build
    - name: install firebase-tools
      run: sudo npm install -g firebase-tools
    - name: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase deploy --token $FIREBASE_TOKEN --project okaryo-portfolio --only hosting

  deploy_firebase_functions:
    name: deploy firebase functions
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: npm install
      working-directory: ./functions
      run: npm install
    - name: install firebase-tools
      run: sudo npm install -g firebase-tools
    - name: set config
      env:
        GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase functions:config:set gmail.email=$GMAIL_EMAIL gmail.password=$GMAIL_PASS admin.email=$ADMIN_EMAIL --token $FIREBASE_TOKEN --project okaryo-portfolio
    - name: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase deploy --only functions --debug
