name: Build and Deploy

on: 
  push:
    branches: 
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: npm install
      run: npm install
    - name: build
      run: npm run build
    - name: persist to workspace
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: download workspace
      uses: actions/download-artifact@master
      with:
        name: build
        path: build
    - name: install firebase-tools
      run: sudo npm install -g firebase-tools
    - name: deploy
      run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
