name: Build and Deploy

on: 
  push:
    branches: 
      - main

jobs:
  build_firebase_hosting:
    name: build firebase hosting
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: npm install
      run: npm install
    - name: build
      run: npm run build
      env:
        REACT_APP_SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: persist to workspace
      uses: actions/upload-artifact@main
      with:
        name: build firebase hosting
        path: ./build

  deploy_firebase_hosting:
    name: deploy firebase hosting
    needs: build_firebase_hosting
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: download workspace
      uses: actions/download-artifact@main
      with:
        name: build firebase hosting
        path: ./build
    - name: install firebase-tools
      run: sudo npm install -g firebase-tools
    - name: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase deploy --only hosting --token $FIREBASE_TOKEN --project okaryo-portfolio
